# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: schlumpfen.de
email: stefan@roschewitz.de
description: >- # this means to ignore newlines until "baseurl:"
  Web Seite von Stefan Roschewitz. Auf dieser Seite versuche
  ich verschiedene Dinge zu posten, die mir wichtig sind bzw. einfallen.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://schlumpfen.de" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  schlumpfen

theme: no-style-please

# Build settings
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
