name: Build Jekyll Pages

on:
  workflow_dispatch:

  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: actions/jekyll-build-pages@v1
        with:
          verbose: true
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./output"
