name: Erstelle Jekyll Seiten

on:
  workflow_dispatch:
  push:
    paths:
      - '_config.yml'
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
         ruby-version: '3.2'

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Jekyll Site
      run: |
        export JEKYLL_ENV=production
        bundle exec jekyll build --trace

    - name: Show all
      run: |
        tree -D . 
        
    - name: Upload artefact
      uses: actions/upload-artifact@v4
      with:  
        name: Webseiten
        path: _site
      
#    - name: Add and commit
#      uses: EndBug/add-and-commit@v9
#      with:
#        default_author: github_actions
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: rsync deployments
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete
        path: _site/
        remote_path: /var/www/virtual/${{ secrets.UBERSPACE_USER }}/schlumpfen.de/
        remote_host: ${{ secrets.UBERSPACE_HOST }}
        remote_user: ${{ secrets.UBERSPACE_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY_PRIVATE }}
