name: Build Jekyll Pages

on:
  workflow_dispatch:

  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: actions/jekyll-build-pages@v1
      - name: Upload/Copy
        uses: actions/upload-artifact@v4
      - name: Download/Copy
        uses: actions/download-artifact@v4
      - name: Display structure of downloaded files
        run: ls -R


      
