name: Erstelle Jekyll Seiten

on:
  workflow_dispatch:
  push:
    paths:
      - '_config.yml'
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
         ruby-version: '3.2'

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Jekyll Site
      run: |
        bundle exec jekyll build
#
#    - name: Create _site Directory
#      run: mkdir _site
#
#    - name: Copy Generated Files to _site
#      run: cp -r _site/* ./_site
#
    - name: Commit and Push Changes
      run: |
        tree ./_site 
        
    - name: Upload
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
