name: Build Jekyll Pages

on:
  workflow_dispatch:
  push:
    paths:
      - '_config.yml'
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Jekyll Site
      run: |
        bundle exec jekyll build

    - name: Create _site Directory
      run: mkdir _site

    - name: Copy Generated Files to _site
      run: cp -r _site/* ./_site

    - name: Commit and Push Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Build Jekyll site"
        git push
